name: habitica → notion sync

on:
  workflow_dispatch:
  schedule:
    # runs once daily at 15:00 UTC → 10:00 AM CDT
    - cron: '0 15 * * *'

jobs:
  update-daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install deps
        run: npm install @notionhq/client dotenv

      - name: run sync
        env:
          HAB_USER:       ${{ secrets.HAB_USER }}
          HAB_KEY:        ${{ secrets.HAB_KEY }}
          NOTION_TOKEN:   ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node sync.js
